[template]
src = "cinder.conf.tmpl"
dest = "/etc/cinder/cinder.conf"
keys = [
    "/services/cinder/config/",
    "/services/rabbitmq/hosts",
    "/services/rabbitmq/config/userid",
    "/services/rabbitmq/config/password",
    "/services/keystone/config/admin-token",
    "/services/cinder/config/db-connection",
    "/services/router/frontend/glance/api",
    "/services/keystone/config/admin-token",
    "/services/balancer/host",
]

reload_cmd="sv restart cinder-scheduler"
