[template]
src = "ceph.conf.tmpl"
dest = "/etc/ceph/ceph.conf"
keys = [
    "/services/ceph/config/mon-addr",
    "/services/ceph/config/public-network",
    "/services/ceph/config/cluster-network",
    "/services/ceph/config/fsid"
]
